swagger: "2.0"
info:
  title: "Agenda"
  description: "API para controle de contatos"
  version: "1.0.0"
host: "localhost:3000"
basePath: "/v1"
schemes: 
  - "http"
paths:
  /contatos:
    post:
      tags:
        - "Contatos"
      summary: "Gravar os dados do contato"
      description: "Os dados do contato serão enviados via body"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: "header"
        name: "access"
        type: "string"
        required: true
        description: "Parâmetro de acesso para consumo do recurso"
      - in: "body"
        name: "contato"
        schema:
          $ref: "#/definitions/Contato"
      responses:
        "201":
          description: "Contato salvo com sucesso"
        "400":
          description: "Dados de envio incorretos"
  
  /contatos/{id}:
    get:
      tags: 
        - "Contatos"
      summary: "Selecionar o registro pelo ID"
      description: "O registro será informado via path"
      produces:
        - "application/json"
      parameters:
      - name: "id"
        required: true
        in: "path"
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Retorno do registro do banco de dados"
          schema:
            $ref: "#/definitions/Contato"
        "204":
          description: "Não foi encontrado nenhum resultado"
      
    delete:
      tags: 
        - "Contatos"
      summary: "Selecionar o registro pelo ID"
      description: "O registro será informado via path"
      produces:
        - "application/json"
      parameters:
      - name: "id"
        required: true
        in: "path"
        type: "integer"
        format: "int64"
      responses:
        "201":
          description: "Retorno do registro do banco de dados"
        "204":
          description: "Não foi encontrado nenhum resultado"

          
definitions:
  Contato:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      idade:
        type: "integer"
        format: "int64"
      email:
        type: "string"
      telefone:
        type: "string"
